import type {
  AnalyticsEntry,
  AnalyticsPeriod,
  Order,
  Payment,
  Product,
  ProductCategory,
  StoreSettings,
} from "@/app/lib/types";
import { getSupabaseBrowserClient } from "@/app/lib/supabase/client";

export const categories: Array<{
  label: ProductCategory;
  description: string;
  // Free-to-use (Unsplash License) stock photos representing each category,
  // chosen to reflect our core customers: Black women and men across a range of skin tones.
  image: string;
}> = [
  {
    label: "Face Care",
    description: "Cleansers, serums, moisturizers and daily skin essentials, including our Korean Skincare (K-beauty) collection.",
    image: "https://images.unsplash.com/photo-1527203561188-dae1bc1a417f?auto=format&fit=crop&w=800&q=80",
  },
  {
    label: "Body Care",
    description: "Body wash, lotion, scrubs and nourishing self-care staples.",
    image: "https://images.unsplash.com/photo-1607187517174-1aa8ff91d93c?auto=format&fit=crop&w=800&q=80",
  },
  {
    label: "Hair Care",
    description: "Shampoo, conditioner, hair oils and scalp treatments.",
    image: "https://images.unsplash.com/photo-1589156191108-c762ff4b96ab?auto=format&fit=crop&w=800&q=80",
  },
  {
    label: "Men's Grooming",
    description: "Beard care, shaving, grooming and everyday essentials.",
    image: "https://images.unsplash.com/photo-1531901599143-df5010ab9438?auto=format&fit=crop&w=800&q=80",
  },
  {
    label: "Makeup",
    description: "Base, eye, lip and beauty tools for every look.",
    image: "https://images.unsplash.com/photo-1593351799227-75df2026356b?auto=format&fit=crop&w=800&q=80",
  },
  {
    label: "Fragrances",
    description: "Perfumes, body sprays and scent collections for all occasions, including our Arabic Perfumes collection.",
    image: "https://images.unsplash.com/photo-1602532381225-eec578361933?auto=format&fit=crop&w=800&q=80",
  },
  {
    label: "Accessories",
    description: "Beauty tools, brushes, mirrors and organizers.",
    image: "https://images.unsplash.com/photo-1592520113018-180c8bc831c9?auto=format&fit=crop&w=800&q=80",
  },
  {
    label: "Baby Care",
    description: "Gentle products for baby skin, bath time and comfort.",
    image: "https://images.unsplash.com/photo-1518200925927-aa63b1e57a84?auto=format&fit=crop&w=800&q=80",
  },
];

export const validReferralCodes = [
  { code: "SELECT10", discountPercent: 10, label: "10% welcome reward" },
  { code: "SELECT15", discountPercent: 15, label: "15% VIP reward" },
  { code: "GLOWUP", discountPercent: 5, label: "5% glow reward" },
] as const;

export function getReferralCodeShareLink(code: string) {
  if (typeof window === "undefined") {
    return `/referrals?ref=${encodeURIComponent(code)}`;
  }

  return `${window.location.origin}/referrals?ref=${encodeURIComponent(code)}`;
}

export function normalizeReferralCode(code: string | undefined) {
  return (code ?? "").trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
}

export function getReferralReward(code: string | undefined) {
  const normalized = normalizeReferralCode(code);
  return validReferralCodes.find((entry) => entry.code === normalized) ?? null;
}

export function getReferralSummary(orders: Order[]) {
  const counts = new Map<string, number>();

  orders.forEach((order) => {
    const normalized = normalizeReferralCode(order.referralCode);
    if (!normalized) {
      return;
    }

    counts.set(normalized, (counts.get(normalized) ?? 0) + 1);
  });

  return Array.from(counts.entries()).map(([code, count]) => ({
    code,
    count,
    reward: getReferralReward(code),
  }));
}

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    name: "Cerave Hydrating Cleanser",
    slug: "cerave-hydrating-cleanser",
    category: "Face Care",
    subcategory: "Cleansers",
    brand: "CeraVe",
    sku: "SS-FC-CER-001",
    productType: "Cleanser",
    description: "A gentle hydrating cleanser that removes impurities while supporting the skin barrier.",
    shortDescription: "Gentle daily cleanser",
    benefits: ["Hydrates", "Cleanses", "Barrier support"],
    ingredients: ["Ceramides", "Hyaluronic acid"],
    instructions: "Massage onto damp skin and rinse thoroughly.",
    size: "236ml",
    suitableFor: ["Dry skin", "Normal skin", "Sensitive skin"],
    price: 185,
    originalPrice: 220,
    discount: 16,
    stock: 24,
    stockStatus: "IN STOCK",
    image: "🧴",
    rating: 4.8,
    reviewCount: 128,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-2",
    name: "Vitamin C Glow Serum",
    slug: "vitamin-c-glow-serum",
    category: "Face Care",
    subcategory: "Serums",
    brand: "Zhurie & Co",
    sku: "SS-FC-SER-002",
    productType: "Serum",
    description: "Brightening serum designed to support a smoother, more radiant complexion.",
    shortDescription: "Brightening serum for glow",
    benefits: ["Brightens", "Smooths", "Radiance support"],
    ingredients: ["Vitamin C", "Niacinamide"],
    instructions: "Apply a few drops before moisturizer.",
    size: "30ml",
    suitableFor: ["Dull skin", "Uneven tone"],
    price: 265,
    originalPrice: 300,
    discount: 12,
    stock: 8,
    stockStatus: "LOW STOCK",
    image: "✨",
    rating: 4.9,
    reviewCount: 84,
    featured: true,
    newArrival: true,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-3",
    name: "Shea Body Butter",
    slug: "shea-body-butter",
    category: "Body Care",
    subcategory: "Body Lotion",
    brand: "Zhurie & Co",
    sku: "SS-BD-BUT-003",
    productType: "Body Butter",
    description: "Rich, comforting body butter that melts into the skin for long-lasting softness.",
    shortDescription: "Deep moisture for dry skin",
    benefits: ["Softens", "Nourishes", "Long-lasting moisture"],
    ingredients: ["Shea butter", "Cocoa butter"],
    instructions: "Apply after showering or whenever skin feels dry.",
    size: "250ml",
    suitableFor: ["Dry skin", "Very dry skin"],
    price: 210,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "🫧",
    rating: 4.7,
    reviewCount: 61,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "SALE",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-4",
    name: "Beard Growth Oil",
    slug: "beard-growth-oil",
    category: "Men's Grooming",
    subcategory: "Beard Care",
    brand: "Noir Grooming",
    sku: "SS-MG-BRD-004",
    productType: "Beard Oil",
    description: "Nourishing beard and skin oil that helps soften hair and improve grooming comfort.",
    shortDescription: "Softens beard and skin",
    benefits: ["Softens", "Conditions", "Lightweight finish"],
    ingredients: ["Argan oil", "Jojoba oil"],
    instructions: "Warm a few drops between hands and work through beard.",
    size: "50ml",
    suitableFor: ["Beards", "Daily grooming"],
    price: 190,
    stock: 6,
    stockStatus: "LOW STOCK",
    image: "🪵",
    rating: 4.6,
    reviewCount: 39,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "TRENDING",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-5",
    name: "Velvet Lash Mascara",
    slug: "velvet-lash-mascara",
    category: "Makeup",
    subcategory: "Eye Makeup",
    brand: "Maison Glow",
    sku: "SS-MK-MAS-005",
    productType: "Mascara",
    description: "Lengthening mascara for defined, lifted lashes and an elegant finish.",
    shortDescription: "Defined lashes in one swipe",
    benefits: ["Lengthens", "Defines", "Buildable formula"],
    ingredients: ["Vitamin E"],
    instructions: "Apply from root to tip, layering as desired.",
    size: "12ml",
    suitableFor: ["Everyday makeup", "Evening looks"],
    price: 225,
    originalPrice: 250,
    discount: 10,
    stock: 14,
    stockStatus: "IN STOCK",
    image: "💄",
    rating: 4.5,
    reviewCount: 52,
    featured: false,
    newArrival: true,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-6",
    name: "Rose Oud Eau de Parfum",
    slug: "rose-oud-eau-de-parfum",
    category: "Fragrances",
    subcategory: "Perfumes",
    brand: "Select Fragrance",
    sku: "SS-FR-ROU-006",
    productType: "Eau de Parfum",
    description: "Elegant floral-oud fragrance with a warm, premium feel for day or evening wear.",
    shortDescription: "Soft floral signature scent",
    benefits: ["Long-lasting", "Elegant", "Warm scent trail"],
    size: "50ml",
    price: 340,
    stock: 9,
    stockStatus: "IN STOCK",
    image: "🌸",
    rating: 4.9,
    reviewCount: 77,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-7",
    name: "Beauty Brush Set",
    slug: "beauty-brush-set",
    category: "Accessories",
    subcategory: "Beauty Tools",
    brand: "Select Tools",
    sku: "SS-AC-BRS-007",
    productType: "Brush Set",
    description: "A versatile brush set for foundation, powder, contour and everyday makeup application.",
    shortDescription: "Everyday makeup brush set",
    benefits: ["Soft bristles", "Versatile", "Easy to clean"],
    size: "10 pieces",
    price: 285,
    stock: 12,
    stockStatus: "IN STOCK",
    image: "🪞",
    rating: 4.4,
    reviewCount: 20,
    featured: false,
    newArrival: true,
    bestSeller: false,
    badge: "LIMITED",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-8",
    name: "Baby Calming Lotion",
    slug: "baby-calming-lotion",
    category: "Baby Care",
    subcategory: "Baby Lotion",
    brand: "Tender Care",
    sku: "SS-BC-LOT-008",
    productType: "Baby Lotion",
    description: "Gentle lotion for soft baby skin with a mild, comforting finish.",
    shortDescription: "Gentle daily care for babies",
    benefits: ["Softens", "Gentle", "Comforting"],
    ingredients: ["Oat extract", "Shea butter"],
    instructions: "Apply to clean, dry skin as needed.",
    size: "200ml",
    ageGroup: "Baby",
    price: 175,
    stock: 15,
    stockStatus: "IN STOCK",
    image: "👶",
    rating: 4.8,
    reviewCount: 26,
    featured: false,
    newArrival: true,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-9",
    name: "Lattafa Yara",
    slug: "lattafa-yara",
    category: "Fragrances",
    subcategory: "Arabic - Women's",
    brand: "Lattafa",
    sku: "SS-AP-YAR-009",
    productType: "Eau de Parfum",
    gender: "Women",
    description: "A best-selling feminine fragrance with sweet vanilla, fruity and floral notes for an irresistible everyday signature scent.",
    shortDescription: "Sweet vanilla floral signature scent",
    benefits: ["Long-lasting", "Sweet & feminine", "Everyday signature scent"],
    size: "100ml",
    suitableFor: ["Women"],
    tags: ["Sweet", "Vanilla", "Fruity", "Floral", "Feminine"],
    price: 380,
    stock: 20,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1705936119495-574eeecde4e3?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewCount: 143,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-10",
    name: "Lattafa Khamrah",
    slug: "lattafa-khamrah",
    category: "Fragrances",
    subcategory: "Arabic - Unisex",
    brand: "Lattafa",
    sku: "SS-AP-KHA-010",
    productType: "Eau de Parfum",
    gender: "Unisex",
    description: "A rich gourmand fragrance blending vanilla, cinnamon and amber for a warm, spicy scent loved by men and women alike.",
    shortDescription: "Warm vanilla cinnamon gourmand scent",
    benefits: ["Long-lasting", "Warm & spicy", "Unisex signature scent"],
    size: "100ml",
    suitableFor: ["Men", "Women"],
    tags: ["Vanilla", "Cinnamon", "Sweet", "Amber", "Gourmand"],
    price: 395,
    stock: 18,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1602532381225-eec578361933?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewCount: 121,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-11",
    name: "Afnan 9PM",
    slug: "afnan-9pm",
    category: "Fragrances",
    subcategory: "Arabic - Men's",
    brand: "Afnan",
    sku: "SS-AP-9PM-011",
    productType: "Eau de Parfum",
    gender: "Men",
    description: "A sweet, warm night-time fragrance with vanilla and fruity notes, designed for an unforgettable evening scent.",
    shortDescription: "Sweet vanilla night-time scent",
    benefits: ["Long-lasting", "Warm & sweet", "Evening signature scent"],
    size: "100ml",
    suitableFor: ["Men"],
    tags: ["Sweet", "Vanilla", "Fruity", "Warm", "Night"],
    price: 360,
    stock: 22,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1659415455925-8b8eef9f93d0?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 98,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-12",
    name: "Armaf Club de Nuit Intense Man",
    slug: "armaf-club-de-nuit-intense-man",
    category: "Fragrances",
    subcategory: "Arabic - Men's",
    brand: "Armaf",
    sku: "SS-AP-CDN-012",
    productType: "Eau de Toilette",
    gender: "Men",
    description: "A smoky, fruity and woody masculine fragrance with legendary staying power and fresh, bold character.",
    shortDescription: "Smoky fruity woody signature scent",
    benefits: ["Long-lasting", "Bold & masculine", "Fresh woody trail"],
    size: "105ml",
    suitableFor: ["Men"],
    tags: ["Smoky", "Fruity", "Woody", "Fresh", "Masculine"],
    price: 340,
    stock: 25,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1622618991746-fe6004db3a47?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewCount: 156,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-13",
    name: "Lattafa Asad",
    slug: "lattafa-asad",
    category: "Fragrances",
    subcategory: "Arabic - Men's",
    brand: "Lattafa",
    sku: "SS-AP-ASD-013",
    productType: "Eau de Parfum",
    gender: "Men",
    description: "A spicy amber-woody fragrance built for bold, masculine confidence with a warm, long-lasting scent trail.",
    shortDescription: "Spicy amber woody signature scent",
    benefits: ["Long-lasting", "Bold & masculine", "Warm amber trail"],
    size: "100ml",
    suitableFor: ["Men"],
    tags: ["Spicy", "Amber", "Woody", "Masculine"],
    price: 355,
    stock: 20,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1640869116016-93c00ba94b28?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 89,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-14",
    name: "Lattafa Khamrah Qahwa",
    slug: "lattafa-khamrah-qahwa",
    category: "Fragrances",
    subcategory: "Arabic - Unisex",
    brand: "Lattafa",
    sku: "SS-AP-KHQ-014",
    productType: "Eau de Parfum",
    gender: "Unisex",
    description: "A gourmand coffee and vanilla fragrance with warm spice, a cozy and indulgent scent for any occasion.",
    shortDescription: "Coffee vanilla gourmand scent",
    benefits: ["Long-lasting", "Warm & spicy", "Unisex signature scent"],
    size: "100ml",
    suitableFor: ["Men", "Women"],
    tags: ["Coffee", "Vanilla", "Sweet", "Spicy", "Gourmand"],
    price: 395,
    stock: 16,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 64,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "TRENDING",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-15",
    name: "Lattafa Bade'e Al Oud Oud For Glory",
    slug: "lattafa-oud-for-glory",
    category: "Fragrances",
    subcategory: "Arabic - Unisex",
    brand: "Lattafa",
    sku: "SS-AP-OFG-015",
    productType: "Eau de Parfum",
    gender: "Unisex",
    description: "A luxurious oud, amber and woody fragrance with a spicy edge, crafted for a rich, elegant scent trail.",
    shortDescription: "Luxury oud amber signature scent",
    benefits: ["Long-lasting", "Rich & luxurious", "Unisex signature scent"],
    size: "100ml",
    suitableFor: ["Men", "Women"],
    tags: ["Oud", "Amber", "Woody", "Spicy", "Luxury"],
    price: 420,
    stock: 12,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 47,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "LUXURY",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-16",
    name: "Lattafa Yara Tous",
    slug: "lattafa-yara-tous",
    category: "Fragrances",
    subcategory: "Arabic - Women's",
    brand: "Lattafa",
    sku: "SS-AP-YRT-016",
    productType: "Eau de Parfum",
    gender: "Women",
    description: "A tropical, fruity twist on the beloved Yara scent, blending sweet florals with a juicy, sun-kissed feel.",
    shortDescription: "Tropical fruity floral scent",
    benefits: ["Long-lasting", "Fruity & sweet", "Everyday signature scent"],
    size: "100ml",
    suitableFor: ["Women"],
    tags: ["Fruity", "Tropical", "Sweet", "Floral"],
    price: 380,
    stock: 15,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1709662369957-0cbf9f8452fc?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 58,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-17",
    name: "Lattafa Yara Moi",
    slug: "lattafa-yara-moi",
    category: "Fragrances",
    subcategory: "Arabic - Women's",
    brand: "Lattafa",
    sku: "SS-AP-YRM-017",
    productType: "Eau de Parfum",
    gender: "Women",
    description: "An elegant, sweet floral fragrance with soft vanilla notes, offering a refined take on the Yara collection.",
    shortDescription: "Elegant sweet vanilla floral scent",
    benefits: ["Long-lasting", "Elegant & sweet", "Everyday signature scent"],
    size: "100ml",
    suitableFor: ["Women"],
    tags: ["Sweet", "Vanilla", "Floral", "Elegant"],
    price: 380,
    stock: 14,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 41,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-18",
    name: "Lattafa Fakhar Black",
    slug: "lattafa-fakhar-black",
    category: "Fragrances",
    subcategory: "Arabic - Men's",
    brand: "Lattafa",
    sku: "SS-AP-FKB-018",
    productType: "Eau de Parfum",
    gender: "Men",
    description: "A fresh, spicy woody fragrance with a bold masculine character, perfect for everyday confidence.",
    shortDescription: "Fresh spicy woody signature scent",
    benefits: ["Long-lasting", "Fresh & masculine", "Everyday signature scent"],
    size: "100ml",
    suitableFor: ["Men"],
    tags: ["Fresh", "Spicy", "Woody", "Masculine"],
    price: 345,
    stock: 19,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1458538977777-0549b2370168?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 33,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-19",
    name: "Lattafa Eclaire",
    slug: "lattafa-eclaire",
    category: "Fragrances",
    subcategory: "Arabic - Women's",
    brand: "Lattafa",
    sku: "SS-AP-ECL-019",
    productType: "Eau de Parfum",
    gender: "Women",
    description: "A decadent gourmand fragrance with vanilla and caramel notes, sweet and comforting like a dessert in a bottle.",
    shortDescription: "Vanilla caramel gourmand scent",
    benefits: ["Long-lasting", "Sweet & indulgent", "Everyday signature scent"],
    size: "100ml",
    suitableFor: ["Women"],
    tags: ["Vanilla", "Caramel", "Sweet", "Gourmand"],
    price: 380,
    stock: 11,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1590736704728-f4730bb30770?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 22,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-20",
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    slug: "cosrx-advanced-snail-96-mucin-power-essence",
    category: "Face Care",
    subcategory: "Korean - Essences",
    brand: "COSRX",
    sku: "SS-KS-CSN-020",
    productType: "Essence",
    description: "A lightweight snail mucin essence designed to help hydrate the skin and support a smoother, healthier-looking complexion. Ideal for customers looking for a hydrated and naturally glowing appearance.",
    shortDescription: "Lightweight hydrating snail mucin essence",
    benefits: ["Hydrates", "Supports smoother complexion", "Lightweight feel"],
    size: "100ml",
    suitableFor: ["All Skin Types"],
    tags: ["Dryness", "Dullness", "Dehydrated Skin"],
    price: 380,
    stock: 20,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 96,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-21",
    name: "Beauty of Joseon Relief Sun SPF50+ PA++++",
    slug: "beauty-of-joseon-relief-sun-spf50",
    category: "Face Care",
    subcategory: "Korean - Sunscreen",
    brand: "Beauty of Joseon",
    sku: "SS-KS-BOJ-021",
    productType: "Sunscreen",
    description: "A lightweight Korean sunscreen with a comfortable finish, designed for daily sun protection while leaving the skin feeling moisturized and comfortable.",
    shortDescription: "Lightweight daily sunscreen SPF50+",
    benefits: ["Daily sun protection", "Comfortable finish", "Moisturizing feel"],
    size: "50ml",
    suitableFor: ["Normal", "Dry", "Combination"],
    tags: ["Sun Protection", "Dry Skin", "Dull Skin"],
    price: 390,
    stock: 25,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewCount: 112,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-22",
    name: "SKIN1004 Madagascar Centella Ampoule",
    slug: "skin1004-madagascar-centella-ampoule",
    category: "Face Care",
    subcategory: "Korean - Serums & Ampoules",
    brand: "SKIN1004",
    sku: "SS-KS-SK1-022",
    productType: "Ampoule",
    description: "A lightweight centella-based ampoule designed to soothe and hydrate the skin. A great choice for customers looking for a simple calming skincare step.",
    shortDescription: "Soothing centella ampoule",
    benefits: ["Soothes", "Hydrates", "Calms sensitive-feeling skin"],
    size: "100ml",
    suitableFor: ["Sensitive", "Combination", "Oily"],
    tags: ["Sensitive Skin", "Oily Skin"],
    price: 380,
    stock: 20,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 88,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-23",
    name: "Anua Heartleaf 77% Soothing Toner",
    slug: "anua-heartleaf-77-soothing-toner",
    category: "Face Care",
    subcategory: "Korean - Toners",
    brand: "Anua",
    sku: "SS-KS-ANU-023",
    productType: "Toner",
    description: "A gentle Korean toner formulated around heartleaf extract to help refresh, hydrate and comfort the skin while preparing it for the next steps in a skincare routine.",
    shortDescription: "Gentle heartleaf soothing toner",
    benefits: ["Refreshes", "Hydrates", "Preps skin for routine"],
    size: "270ml",
    suitableFor: ["Oily", "Combination", "Sensitive"],
    tags: ["Oily Skin", "Sensitive Skin", "Uneven Texture"],
    price: 390,
    stock: 15,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1631730359585-38a4935cbec4?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewCount: 104,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-24",
    name: "Beauty of Joseon Glow Serum",
    slug: "beauty-of-joseon-glow-serum",
    category: "Face Care",
    subcategory: "Korean - Serums",
    brand: "Beauty of Joseon",
    sku: "SS-KS-BOJ-024",
    productType: "Serum",
    description: "A lightweight serum designed to give the skin a fresh, hydrated and radiant-looking appearance. Perfect for customers who want a simple glow-focused serum.",
    shortDescription: "Fresh, radiance-focused serum",
    benefits: ["Hydrates", "Supports radiant look", "Lightweight"],
    size: "30ml",
    suitableFor: ["All Skin Types"],
    tags: ["Dull Skin", "Uneven Skin Tone", "Dehydrated Skin"],
    price: 350,
    stock: 20,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 91,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-25",
    name: "COSRX Low pH Good Morning Gel Cleanser",
    slug: "cosrx-low-ph-good-morning-gel-cleanser",
    category: "Face Care",
    subcategory: "Korean - Cleansers",
    brand: "COSRX",
    sku: "SS-KS-CSN-025",
    productType: "Cleanser",
    description: "A low-pH gel cleanser designed to gently remove everyday impurities and excess oil without leaving the skin feeling excessively dry.",
    shortDescription: "Gentle low-pH gel cleanser",
    benefits: ["Cleanses gently", "Removes excess oil", "Balanced pH"],
    size: "150ml",
    suitableFor: ["Oily", "Combination", "Normal"],
    tags: ["Oily Skin"],
    price: 320,
    stock: 15,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1598452963314-b09f397a5c48?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 76,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-26",
    name: "Anua Heartleaf Quercetinol Pore Deep Cleansing Foam",
    slug: "anua-heartleaf-quercetinol-pore-deep-cleansing-foam",
    category: "Face Care",
    subcategory: "Korean - Cleansers",
    brand: "Anua",
    sku: "SS-KS-ANU-026",
    productType: "Cleanser",
    description: "A refreshing foaming cleanser designed to cleanse away impurities and excess oil while providing a comfortable cleansing experience.",
    shortDescription: "Refreshing pore-deep cleansing foam",
    benefits: ["Deep cleanses", "Removes excess oil", "Comfortable feel"],
    size: "150ml",
    suitableFor: ["Oily", "Combination"],
    tags: ["Oily Skin", "Large/Clogged Pores"],
    price: 350,
    stock: 15,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1600428877878-1a0fd85beda8?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 82,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-27",
    name: "SKIN1004 Madagascar Centella Light Cleansing Oil",
    slug: "skin1004-madagascar-centella-light-cleansing-oil",
    category: "Face Care",
    subcategory: "Korean - Cleansing Oils",
    brand: "SKIN1004",
    sku: "SS-KS-SK1-027",
    productType: "Cleansing Oil",
    description: "A lightweight cleansing oil designed to help dissolve makeup, sunscreen and daily impurities as the first step of a double-cleansing routine.",
    shortDescription: "Lightweight double-cleanse oil",
    benefits: ["Dissolves makeup", "Removes sunscreen", "First cleanse step"],
    size: "200ml",
    suitableFor: ["All Skin Types"],
    tags: [],
    price: 390,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1607187517174-1aa8ff91d93c?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 41,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-28",
    name: "Beauty of Joseon Ginseng Cleansing Oil",
    slug: "beauty-of-joseon-ginseng-cleansing-oil",
    category: "Face Care",
    subcategory: "Korean - Cleansing Oils",
    brand: "Beauty of Joseon",
    sku: "SS-KS-BOJ-028",
    productType: "Cleansing Oil",
    description: "A gentle cleansing oil designed to remove makeup, sunscreen and everyday impurities while leaving the skin feeling clean and comfortable.",
    shortDescription: "Gentle ginseng cleansing oil",
    benefits: ["Removes makeup", "Removes sunscreen", "Comfortable finish"],
    size: "210ml",
    suitableFor: ["All Skin Types"],
    tags: [],
    price: 390,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 39,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-29",
    name: "COSRX BHA Blackhead Power Liquid",
    slug: "cosrx-bha-blackhead-power-liquid",
    category: "Face Care",
    subcategory: "Korean - Treatments",
    brand: "COSRX",
    sku: "SS-KS-CSN-029",
    productType: "Treatment",
    description: "A BHA exfoliating treatment designed for customers who want to improve the appearance of clogged pores, blackheads and uneven-looking skin texture.",
    shortDescription: "BHA exfoliating pore treatment",
    benefits: ["Targets blackheads", "Improves texture appearance", "Exfoliates"],
    size: "100ml",
    suitableFor: ["Oily", "Combination"],
    tags: ["Large/Clogged Pores", "Uneven Texture", "Acne & Blemishes"],
    price: 370,
    stock: 15,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 67,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-30",
    name: "Beauty of Joseon Glow Deep Serum",
    slug: "beauty-of-joseon-glow-deep-serum",
    category: "Face Care",
    subcategory: "Korean - Serums",
    brand: "Beauty of Joseon",
    sku: "SS-KS-BOJ-030",
    productType: "Serum",
    description: "A lightweight brightening-focused serum designed to help improve the appearance of dull and uneven-looking skin while supporting a radiant complexion.",
    shortDescription: "Brightening-focused glow serum",
    benefits: ["Brightening focus", "Supports radiance", "Lightweight"],
    size: "30ml",
    suitableFor: ["All Skin Types"],
    tags: ["Dull Skin", "Uneven Skin Tone", "Dark Spots"],
    price: 370,
    stock: 15,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewCount: 73,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-31",
    name: "Anua Niacinamide 10% + TXA 4% Serum",
    slug: "anua-niacinamide-10-txa-4-serum",
    category: "Face Care",
    subcategory: "Korean - Serums",
    brand: "Anua",
    sku: "SS-KS-ANU-031",
    productType: "Serum",
    description: "A targeted serum combining niacinamide and tranexamic acid to support a more even-looking and radiant complexion.",
    shortDescription: "Niacinamide + TXA targeted serum",
    benefits: ["Supports even tone", "Radiance support", "Targeted formula"],
    size: "30ml",
    suitableFor: ["Combination", "Oily", "Normal"],
    tags: ["Uneven Skin Tone", "Dull Skin", "Dark Spots"],
    price: 450,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 58,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-32",
    name: "SKIN1004 Tone Brightening Ampoule",
    slug: "skin1004-tone-brightening-ampoule",
    category: "Face Care",
    subcategory: "Korean - Serums & Ampoules",
    brand: "SKIN1004",
    sku: "SS-KS-SK1-032",
    productType: "Ampoule",
    description: "A brightening-focused ampoule designed to support a more radiant and even-looking complexion while providing lightweight hydration.",
    shortDescription: "Brightening-focused ampoule",
    benefits: ["Radiance support", "Lightweight hydration", "Even-looking tone"],
    size: "100ml",
    suitableFor: ["All Skin Types"],
    tags: ["Dull Skin", "Uneven Skin Tone"],
    price: 420,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1631730359585-38a4935cbec4?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 44,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-33",
    name: "Beauty of Joseon Revive Serum",
    slug: "beauty-of-joseon-revive-serum",
    category: "Face Care",
    subcategory: "Korean - Serums",
    brand: "Beauty of Joseon",
    sku: "SS-KS-BOJ-033",
    productType: "Serum",
    description: "A nourishing serum designed to hydrate and support a smoother, healthier-looking complexion.",
    shortDescription: "Nourishing hydrating serum",
    benefits: ["Hydrates", "Nourishes", "Supports smoother look"],
    size: "30ml",
    suitableFor: ["Normal", "Dry", "Mature"],
    tags: ["Dry Skin", "Dull Skin", "Anti-Ageing"],
    price: 370,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 29,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-34",
    name: "Torriden Dive-In Hyaluronic Acid Serum",
    slug: "torriden-dive-in-hyaluronic-acid-serum",
    category: "Face Care",
    subcategory: "Korean - Serums",
    brand: "Torriden",
    sku: "SS-KS-TOR-034",
    productType: "Serum",
    description: "A lightweight hydrating serum designed to provide moisture and leave the skin feeling fresh, soft and comfortable.",
    shortDescription: "Lightweight hydrating serum",
    benefits: ["Hydrates", "Fresh feel", "Soft, comfortable skin"],
    size: "50ml",
    suitableFor: ["All Skin Types"],
    tags: ["Dehydrated Skin", "Dry Skin"],
    price: 420,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1598452963314-b09f397a5c48?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 53,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-35",
    name: "COSRX Snail 92 All In One Cream",
    slug: "cosrx-snail-92-all-in-one-cream",
    category: "Face Care",
    subcategory: "Korean - Moisturizers",
    brand: "COSRX",
    sku: "SS-KS-CSN-035",
    productType: "Moisturizer",
    description: "A nourishing moisturizer designed to provide hydration and help support a smooth, comfortable skin barrier.",
    shortDescription: "Nourishing all-in-one cream",
    benefits: ["Hydrates", "Supports skin barrier", "Smooth, comfortable feel"],
    size: "100ml",
    suitableFor: ["Normal", "Dry", "Combination"],
    tags: ["Dry Skin", "Dehydrated Skin", "Dull Skin"],
    price: 420,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1600428877878-1a0fd85beda8?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 61,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-36",
    name: "Beauty of Joseon Dynasty Cream",
    slug: "beauty-of-joseon-dynasty-cream",
    category: "Face Care",
    subcategory: "Korean - Moisturizers",
    brand: "Beauty of Joseon",
    sku: "SS-KS-BOJ-036",
    productType: "Moisturizer",
    description: "A rich yet comfortable moisturizer designed to hydrate the skin and provide a healthy-looking glow.",
    shortDescription: "Rich, comfortable glow cream",
    benefits: ["Hydrates", "Healthy-looking glow", "Comfortable finish"],
    size: "50ml",
    suitableFor: ["Normal", "Dry", "Combination"],
    tags: ["Dry Skin", "Dehydrated Skin", "Dull Skin"],
    price: 450,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1607187517174-1aa8ff91d93c?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 47,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-37",
    name: "SKIN1004 Centella Soothing Cream",
    slug: "skin1004-centella-soothing-cream",
    category: "Face Care",
    subcategory: "Korean - Moisturizers",
    brand: "SKIN1004",
    sku: "SS-KS-SK1-037",
    productType: "Moisturizer",
    description: "A lightweight soothing moisturizer designed to provide comfort while helping to calm sensitive-feeling skin.",
    shortDescription: "Lightweight soothing moisturizer",
    benefits: ["Soothes", "Hydrates", "Calms sensitive-feeling skin"],
    size: "100ml",
    suitableFor: ["Sensitive", "Combination", "Oily"],
    tags: ["Sensitive Skin", "Dry Skin"],
    price: 390,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 38,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-38",
    name: "Anua 3 Ceramide Panthenol Cream",
    slug: "anua-3-ceramide-panthenol-cream",
    category: "Face Care",
    subcategory: "Korean - Moisturizers",
    brand: "Anua",
    sku: "SS-KS-ANU-038",
    productType: "Moisturizer",
    description: "A nourishing cream designed to provide moisture and support the skin's natural barrier, making it suitable for dry and sensitive-feeling skin.",
    shortDescription: "Nourishing barrier support cream",
    benefits: ["Hydrates", "Supports skin barrier", "Nourishes"],
    size: "80ml",
    suitableFor: ["Dry", "Sensitive", "Normal"],
    tags: ["Dry Skin", "Sensitive Skin", "Skin Barrier Support"],
    price: 450,
    stock: 8,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 34,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-39",
    name: "COSRX Acne Pimple Master Patch",
    slug: "cosrx-acne-pimple-master-patch",
    category: "Face Care",
    subcategory: "Korean - Acne Care",
    brand: "COSRX",
    sku: "SS-KS-CSN-039",
    productType: "Acne Patch",
    description: "Convenient hydrocolloid patches designed to cover individual blemishes and help protect the area from external impurities.",
    shortDescription: "Hydrocolloid blemish patches",
    benefits: ["Covers blemishes", "Protects from impurities", "Convenient wear"],
    size: "24 patches",
    suitableFor: ["Oily", "Combination", "Normal"],
    tags: ["Acne & Blemishes"],
    price: 150,
    stock: 25,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewCount: 118,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-40",
    name: "Beauty of Joseon Green Plum Refreshing Cleanser",
    slug: "beauty-of-joseon-green-plum-refreshing-cleanser",
    category: "Face Care",
    subcategory: "Korean - Cleansers",
    brand: "Beauty of Joseon",
    sku: "SS-KS-BOJ-040",
    productType: "Cleanser",
    description: "A gentle daily cleanser designed to remove everyday impurities while leaving the skin feeling clean and refreshed.",
    shortDescription: "Gentle daily refreshing cleanser",
    benefits: ["Cleanses gently", "Refreshes", "Daily use"],
    size: "150ml",
    suitableFor: ["All Skin Types"],
    tags: [],
    price: 330,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 27,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-41",
    name: "COSRX Vitamin C 23% Serum",
    slug: "cosrx-vitamin-c-23-serum",
    category: "Face Care",
    subcategory: "Korean - Serums",
    brand: "COSRX",
    sku: "SS-KS-CSN-041",
    productType: "Serum",
    description: "A concentrated vitamin C serum designed for customers looking to add a brightening-focused step to their skincare routine.",
    shortDescription: "Concentrated brightening vitamin C serum",
    benefits: ["Brightening focus", "Concentrated formula", "Radiance support"],
    size: "20ml",
    suitableFor: ["Normal", "Combination", "Oily"],
    tags: ["Dull Skin", "Uneven Skin Tone"],
    price: 390,
    stock: 8,
    stockStatus: "LOW STOCK",
    image: "https://images.unsplash.com/photo-1631730359585-38a4935cbec4?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 51,
    featured: true,
    newArrival: false,
    bestSeller: false,
    badge: "NEW",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-42",
    name: "Beauty of Joseon Light On Serum",
    slug: "beauty-of-joseon-light-on-serum",
    category: "Face Care",
    subcategory: "Korean - Serums",
    brand: "Beauty of Joseon",
    sku: "SS-KS-BOJ-042",
    productType: "Serum",
    description: "A lightweight serum designed to support a brighter and more radiant-looking complexion without feeling heavy on the skin.",
    shortDescription: "Lightweight radiance serum",
    benefits: ["Brightening focus", "Lightweight feel", "Radiance support"],
    size: "30ml",
    suitableFor: ["All Skin Types"],
    tags: ["Dull Skin", "Uneven Skin Tone"],
    price: 370,
    stock: 8,
    stockStatus: "LOW STOCK",
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 22,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-43",
    name: "SKIN1004 Hyalu-Cica Water-Fit Sun Serum SPF50+",
    slug: "skin1004-hyalu-cica-water-fit-sun-serum-spf50",
    category: "Face Care",
    subcategory: "Korean - Sunscreen",
    brand: "SKIN1004",
    sku: "SS-KS-SK1-043",
    productType: "Sunscreen",
    description: "A lightweight daily sunscreen designed to provide high SPF protection while giving the skin a comfortable, hydrated finish.",
    shortDescription: "Lightweight hydrating sun serum SPF50+",
    benefits: ["High SPF protection", "Hydrating finish", "Lightweight, daily wear"],
    size: "50ml",
    suitableFor: ["All Skin Types"],
    tags: ["Sun Protection", "Dry Skin", "Dehydrated Skin"],
    price: 420,
    stock: 15,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1600428877878-1a0fd85beda8?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 64,
    featured: true,
    newArrival: false,
    bestSeller: true,
    badge: "BEST SELLER",
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-44",
    name: "Anua Heartleaf 70% Mud Cream Pore Mask",
    slug: "anua-heartleaf-70-mud-cream-pore-mask",
    category: "Face Care",
    subcategory: "Korean - Face Masks",
    brand: "Anua",
    sku: "SS-KS-ANU-044",
    productType: "Mask",
    description: "A pore-care mask designed for customers looking for a deeper cleansing step to help remove impurities and excess oil.",
    shortDescription: "Deep pore-care mud mask",
    benefits: ["Deep cleansing", "Removes excess oil", "Targets clogged pores"],
    size: "105ml",
    suitableFor: ["Oily", "Combination"],
    tags: ["Oily Skin", "Large/Clogged Pores"],
    price: 390,
    stock: 6,
    stockStatus: "LOW STOCK",
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 19,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-45",
    name: "COSRX AHA 7 Whitehead Power Liquid",
    slug: "cosrx-aha-7-whitehead-power-liquid",
    category: "Face Care",
    subcategory: "Korean - Treatments",
    brand: "COSRX",
    sku: "SS-KS-CSN-045",
    productType: "Treatment",
    description: "An AHA exfoliating treatment designed to help improve the appearance of uneven skin texture and dull-looking skin.",
    shortDescription: "AHA exfoliating texture treatment",
    benefits: ["Exfoliates", "Improves texture appearance", "Brightening focus"],
    size: "100ml",
    suitableFor: ["Normal", "Combination", "Oily"],
    tags: ["Uneven Texture", "Dull Skin"],
    price: 370,
    stock: 8,
    stockStatus: "LOW STOCK",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 31,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-46",
    name: "Beauty of Joseon Revive Eye Serum",
    slug: "beauty-of-joseon-revive-eye-serum",
    category: "Face Care",
    subcategory: "Korean - Eye Care",
    brand: "Beauty of Joseon",
    sku: "SS-KS-BOJ-046",
    productType: "Eye Serum",
    description: "A nourishing eye serum designed to hydrate the delicate eye area and support a smoother, refreshed-looking appearance.",
    shortDescription: "Hydrating eye serum",
    benefits: ["Hydrates eye area", "Refreshed-looking appearance", "Nourishing formula"],
    size: "30ml",
    suitableFor: ["All Skin Types"],
    tags: ["Dry Skin", "Anti-Ageing"],
    price: 370,
    stock: 8,
    stockStatus: "LOW STOCK",
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 24,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-47",
    name: "SKIN1004 Centella Ampoule Foam",
    slug: "skin1004-centella-ampoule-foam",
    category: "Face Care",
    subcategory: "Korean - Cleansers",
    brand: "SKIN1004",
    sku: "SS-KS-SK1-047",
    productType: "Cleanser",
    description: "A gentle foaming cleanser designed to remove daily impurities while providing a comfortable cleansing experience.",
    shortDescription: "Gentle centella foaming cleanser",
    benefits: ["Cleanses gently", "Comfortable feel", "Daily use"],
    size: "150ml",
    suitableFor: ["All Skin Types"],
    tags: ["Sensitive Skin"],
    price: 350,
    stock: 10,
    stockStatus: "IN STOCK",
    image: "https://images.unsplash.com/photo-1600428877878-1a0fd85beda8?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 33,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-48",
    name: "Anua Rice Ceramide Hydrating Barrier Serum",
    slug: "anua-rice-ceramide-hydrating-barrier-serum",
    category: "Face Care",
    subcategory: "Korean - Serums",
    brand: "Anua",
    sku: "SS-KS-ANU-048",
    productType: "Serum",
    description: "A hydrating serum designed to support moisture levels and help the skin feel softer, smoother and more comfortable.",
    shortDescription: "Hydrating barrier support serum",
    benefits: ["Hydrates", "Supports skin barrier", "Softer, smoother feel"],
    size: "30ml",
    suitableFor: ["Dry", "Sensitive", "Normal"],
    tags: ["Dehydrated Skin", "Dry Skin", "Skin Barrier Support"],
    price: 450,
    stock: 8,
    stockStatus: "LOW STOCK",
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 28,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-49",
    name: "Torriden Dive-In Low Molecular Hyaluronic Acid Cream",
    slug: "torriden-dive-in-low-molecular-hyaluronic-acid-cream",
    category: "Face Care",
    subcategory: "Korean - Moisturizers",
    brand: "Torriden",
    sku: "SS-KS-TOR-049",
    productType: "Moisturizer",
    description: "A hydrating moisturizer designed to provide comfortable daily moisture and leave the skin feeling soft, smooth and refreshed.",
    shortDescription: "Hydrating daily moisturizer",
    benefits: ["Hydrates", "Soft, smooth feel", "Daily comfort"],
    size: "80ml",
    suitableFor: ["All Skin Types"],
    tags: ["Dehydrated Skin", "Dry Skin"],
    price: 450,
    stock: 8,
    stockStatus: "LOW STOCK",
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 26,
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date().toISOString(),
  },
];

export const initialSettings: StoreSettings = {
  storeName: "Zhurie & Co",
  storeLogo: "/favicon.ico",
  storeEmail: "hello@skincareselect.co.zm",
  phoneNumber: "+260977000000",
  whatsappNumber: "+260977000000",
  mtnNumber: "+260770000001",
  airtelNumber: "+260960000001",
  zamtelNumber: "+260950000001",
  bankName: "Zanaco",
  bankAccountName: "Zhurie & Co Zambia",
  bankAccountNumber: "0101234567",
  bankBranch: "Lusaka",
  supportEmail: "hello@skincareselect.co.zm",
  supportPhone: "+260977000000",
  paymentNumbers: {
    "MTN Mobile Money": "+260770000001",
    "Airtel Money": "+260960000001",
    "Zamtel Money": "+260950000001",
    "Bank Transfer": "0101234567",
    "Cash on Delivery": "+260977000000",
  },
  bankDetails: {
    accountName: "Zhurie & Co Zambia",
    accountNumber: "0101234567",
    bankName: "Zanaco",
    branch: "Lusaka",
    swiftCode: "ZANAZMLU",
  },
  deliveryFee: 50,
  currency: "ZMW",
  businessHours: "Mon-Sat: 8:00 AM - 8:00 PM",
  socialLinks: {
    instagram: "https://instagram.com/skincareselect",
    facebook: "https://facebook.com/skincareselect",
    tiktok: "https://tiktok.com/@skincareselect",
  },
};

const STORAGE_KEYS = {
  products: "skincare-select-products",
  orders: "skincare-select-orders",
  payments: "skincare-select-payments",
  settings: "skincare-select-settings",
  analytics: "skincare-select-analytics",
};

function getDateKey(date: Date, period: AnalyticsPeriod) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");

  if (period === "day") {
    return `${year}-${month}-${day}`;
  }

  const start = new Date(date);
  const dayOfWeek = (start.getDay() + 6) % 7;
  start.setDate(start.getDate() - dayOfWeek);
  const weekStart = new Date(start.getFullYear(), start.getMonth(), start.getDate());

  if (period === "week") {
    return `${weekStart.getFullYear()}-${String(weekStart.getMonth() + 1).padStart(2, "0")}-${String(weekStart.getDate()).padStart(2, "0")}`;
  }

  return `${year}-${month}`;
}

export function getAnalyticsEntries(): AnalyticsEntry[] {
  return safeRead<AnalyticsEntry[]>(STORAGE_KEYS.analytics, []);
}

export function saveAnalyticsEntries(entries: AnalyticsEntry[]) {
  safeWrite(STORAGE_KEYS.analytics, entries);
}

export function computeAnalyticsSummary(entries: AnalyticsEntry[]) {
  const now = new Date();
  const dayKey = `day:${getDateKey(now, "day")}`;
  const weekKey = `week:${getDateKey(now, "week")}`;
  const monthKey = `month:${getDateKey(now, "month")}`;

  return {
    day: entries
      .filter((entry) => entry.period === "day" && entry.periodKey === dayKey)
      .reduce((sum, entry) => sum + entry.visitCount, 0),
    week: entries
      .filter((entry) => entry.period === "week" && entry.periodKey === weekKey)
      .reduce((sum, entry) => sum + entry.visitCount, 0),
    month: entries
      .filter((entry) => entry.period === "month" && entry.periodKey === monthKey)
      .reduce((sum, entry) => sum + entry.visitCount, 0),
  };
}

export function getAnalyticsSummary(): { day: number; week: number; month: number } {
  return computeAnalyticsSummary(getAnalyticsEntries());
}

export async function recordVisitAnalytics() {
  if (typeof window === "undefined") {
    return;
  }

  const sessionKey = "skincare-select-visit-logged";
  if (sessionStorage.getItem(sessionKey)) {
    return;
  }

  const now = new Date();
  const nowIso = now.toISOString();
  const nextEntries = [...getAnalyticsEntries()];

  const periods: Array<{ period: AnalyticsPeriod; periodKey: string }> = [
    { period: "day", periodKey: `day:${getDateKey(now, "day")}` },
    { period: "week", periodKey: `week:${getDateKey(now, "week")}` },
    { period: "month", periodKey: `month:${getDateKey(now, "month")}` },
  ];

  periods.forEach(({ period, periodKey }) => {
    const existing = nextEntries.find((entry) => entry.period === period && entry.periodKey === periodKey);
    if (existing) {
      existing.visitCount += 1;
      existing.updatedAt = nowIso;
      return;
    }

    nextEntries.push({
      id: `analytics-${period}-${periodKey}`,
      period,
      periodKey,
      visitCount: 1,
      createdAt: nowIso,
      updatedAt: nowIso,
    });
  });

  saveAnalyticsEntries(nextEntries);
  sessionStorage.setItem(sessionKey, "true");

  const supabase = getSupabaseBrowserClient();
  if (!supabase) {
    return;
  }

  for (const entry of nextEntries) {
    const { error } = await supabase.from("analytics_visits").upsert(entry, { onConflict: "id" });
    if (error) {
      console.warn("Analytics sync failed:", error.message);
    }
  }
}

function safeRead<T>(key: string, fallback: T): T {
  if (typeof window === "undefined") {
    return fallback;
  }

  try {
    const stored = window.localStorage.getItem(key);
    return stored ? (JSON.parse(stored) as T) : fallback;
  } catch {
    return fallback;
  }
}

function safeWrite<T>(key: string, value: T) {
  if (typeof window === "undefined") {
    return;
  }

  window.localStorage.setItem(key, JSON.stringify(value));
}

export function getProducts(): Product[] {
  return safeRead<Product[]>(STORAGE_KEYS.products, initialProducts);
}

export function saveProducts(products: Product[]) {
  safeWrite(STORAGE_KEYS.products, products);
}

export function getProductBySlug(slug: string): Product | undefined {
  return getProducts().find((product) => product.slug === slug);
}

export function getOrders(): Order[] {
  return safeRead<Order[]>(STORAGE_KEYS.orders, []);
}

export function saveOrders(orders: Order[]) {
  safeWrite(STORAGE_KEYS.orders, orders);
}

export function getPayments(): Payment[] {
  return safeRead<Payment[]>(STORAGE_KEYS.payments, []);
}

export function savePayments(payments: Payment[]) {
  safeWrite(STORAGE_KEYS.payments, payments);
}

export function getSettings(): StoreSettings {
  return safeRead<StoreSettings>(STORAGE_KEYS.settings, initialSettings);
}

export function saveSettings(settings: StoreSettings) {
  safeWrite(STORAGE_KEYS.settings, settings);
}

export function createId(prefix: string) {
  return `${prefix}-${Math.random().toString(36).slice(2, 10)}`;
}
